name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /www/wwwroot/internapp.rittercoding.com
            sudo git reset --hard
            sudo git pull
            sudo sh cicd.sh
            cd /www/wwwroot/
            sudo chown -R www:www internapp.rittercoding.com/
